import ssl as _ssl

AlertDescription = _ssl.AlertDescription
ASN1Object = _ssl._ASN1Object
Options = _ssl.Options
Purpose = _ssl.Purpose
TLSVersion = _ssl.TLSVersion
VerifyFlags = _ssl.VerifyFlags
VerifyMode = _ssl.VerifyMode


# Alert Description
ALERT_DESCRIPTION_ACCESS_DENIED = _ssl.ALERT_DESCRIPTION_ACCESS_DENIED
ALERT_DESCRIPTION_BAD_CERTIFICATE = _ssl.ALERT_DESCRIPTION_BAD_CERTIFICATE
ALERT_DESCRIPTION_BAD_CERTIFICATE_HASH_VALUE = (
    _ssl.ALERT_DESCRIPTION_BAD_CERTIFICATE_HASH_VALUE
)
ALERT_DESCRIPTION_BAD_CERTIFICATE_STATUS_RESPONSE = (
    _ssl.ALERT_DESCRIPTION_BAD_CERTIFICATE_STATUS_RESPONSE
)
ALERT_DESCRIPTION_BAD_RECORD_MAC = _ssl.ALERT_DESCRIPTION_BAD_RECORD_MAC
ALERT_DESCRIPTION_CERTIFICATE_EXPIRED = _ssl.ALERT_DESCRIPTION_CERTIFICATE_EXPIRED
ALERT_DESCRIPTION_CERTIFICATE_REVOKED = _ssl.ALERT_DESCRIPTION_CERTIFICATE_REVOKED
ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN = _ssl.ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN
ALERT_DESCRIPTION_CERTIFICATE_UNOBTAINABLE = (
    _ssl.ALERT_DESCRIPTION_CERTIFICATE_UNOBTAINABLE
)
ALERT_DESCRIPTION_CLOSE_NOTIFY = _ssl.ALERT_DESCRIPTION_CLOSE_NOTIFY
ALERT_DESCRIPTION_DECODE_ERROR = _ssl.ALERT_DESCRIPTION_DECODE_ERROR
ALERT_DESCRIPTION_DECOMPRESSION_FAILURE = _ssl.ALERT_DESCRIPTION_DECOMPRESSION_FAILURE
ALERT_DESCRIPTION_DECRYPT_ERROR = _ssl.ALERT_DESCRIPTION_DECRYPT_ERROR
ALERT_DESCRIPTION_HANDSHAKE_FAILURE = _ssl.ALERT_DESCRIPTION_HANDSHAKE_FAILURE
ALERT_DESCRIPTION_ILLEGAL_PARAMETER = _ssl.ALERT_DESCRIPTION_ILLEGAL_PARAMETER
ALERT_DESCRIPTION_INSUFFICIENT_SECURITY = _ssl.ALERT_DESCRIPTION_INSUFFICIENT_SECURITY
ALERT_DESCRIPTION_INTERNAL_ERROR = _ssl.ALERT_DESCRIPTION_INTERNAL_ERROR
ALERT_DESCRIPTION_NO_RENEGOTIATION = _ssl.ALERT_DESCRIPTION_NO_RENEGOTIATION
ALERT_DESCRIPTION_PROTOCOL_VERSION = _ssl.ALERT_DESCRIPTION_PROTOCOL_VERSION
ALERT_DESCRIPTION_RECORD_OVERFLOW = _ssl.ALERT_DESCRIPTION_RECORD_OVERFLOW
ALERT_DESCRIPTION_UNEXPECTED_MESSAGE = _ssl.ALERT_DESCRIPTION_UNEXPECTED_MESSAGE
ALERT_DESCRIPTION_UNKNOWN_CA = _ssl.ALERT_DESCRIPTION_UNKNOWN_CA
ALERT_DESCRIPTION_UNKNOWN_PSK_IDENTITY = _ssl.ALERT_DESCRIPTION_UNKNOWN_PSK_IDENTITY
ALERT_DESCRIPTION_UNRECOGNIZED_NAME = _ssl.ALERT_DESCRIPTION_UNRECOGNIZED_NAME
ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE = (
    _ssl.ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE
)
ALERT_DESCRIPTION_UNSUPPORTED_EXTENSION = _ssl.ALERT_DESCRIPTION_UNSUPPORTED_EXTENSION
ALERT_DESCRIPTION_USER_CANCELLED = _ssl.ALERT_DESCRIPTION_USER_CANCELLED


# Verify Mode
CERT_NONE = _ssl.CERT_NONE
CERT_OPTIONAL = _ssl.CERT_OPTIONAL
CERT_REQUIRED = _ssl.CERT_REQUIRED


# Options
OP_ALL = _ssl.OP_ALL
OP_CIPHER_SERVER_PREFERENCE = _ssl.OP_CIPHER_SERVER_PREFERENCE
OP_ENABLE_MIDDLEBOX_COMPAT = _ssl.OP_ENABLE_MIDDLEBOX_COMPAT
OP_NO_COMPRESSION = _ssl.OP_NO_COMPRESSION
OP_NO_RENEGOTIATION = _ssl.OP_NO_RENEGOTIATION
OP_NO_TICKET = _ssl.OP_NO_TICKET
OP_SINGLE_DH_USE = _ssl.OP_SINGLE_DH_USE
OP_SINGLE_ECDH_USE = _ssl.OP_SINGLE_ECDH_USE
OP_NO_SSLv2 = _ssl.OP_NO_SSLv2
OP_NO_SSLv3 = _ssl.OP_NO_SSLv3
OP_NO_TLSv1 = _ssl.OP_NO_TLSv1
OP_NO_TLSv1_1 = _ssl.OP_NO_TLSv1_1
OP_NO_TLSv1_2 = _ssl.OP_NO_TLSv1_2
OP_NO_TLSv1_3 = _ssl.OP_NO_TLSv1_3


# PEM
PEM_FOOTER = _ssl.PEM_FOOTER
PEM_HEADER = _ssl.PEM_HEADER


# Protocol
PROTOCOL_TLS = _ssl.PROTOCOL_TLS
PROTOCOL_TLS_CLIENT = _ssl.PROTOCOL_TLS_CLIENT
PROTOCOL_TLS_SERVER = _ssl.PROTOCOL_TLS_SERVER
PROTOCOL_TLSv1 = _ssl.PROTOCOL_TLSv1
PROTOCOL_TLSv1_1 = _ssl.PROTOCOL_TLSv1_1
PROTOCOL_TLSv1_2 = _ssl.PROTOCOL_TLSv1_2


# SSL Error codes
SSL_ERROR_EOF = _ssl.SSL_ERROR_EOF
SSL_ERROR_WANT_READ = _ssl.SSL_ERROR_WANT_READ
SSL_ERROR_WANT_WRITE = _ssl.SSL_ERROR_WANT_WRITE
SSL_ERROR_ZERO_RETURN = _ssl.SSL_ERROR_ZERO_RETURN
SSL_ERROR_SYSCALL = _ssl.SSL_ERROR_SYSCALL


CHANNEL_BINDING_TYPES = _ssl.CHANNEL_BINDING_TYPES
HAS_NEVER_CHECK_COMMON_NAME = _ssl.HAS_NEVER_CHECK_COMMON_NAME
SUPPORTED_TLS_VERSIONS = (
    TLSVersion.TLSv1,
    TLSVersion.TLSv1_1,
    TLSVersion.TLSv1_2,
    TLSVersion.TLSv1_3,
)
