# Copyright (c) 2026 The simple-tls Contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

from ._alert import (
    Alert,
    AlertBadCertificate,
    AlertBadRecordMac,
    AlertCertificateExpired,
    AlertCertificateRequired,
    AlertDecodeError,
    AlertDecryptError,
    AlertECHRequired,
    AlertException,
    AlertHandshakeFailure,
    AlertIllegalParameter,
    AlertInappropriateFallback,
    AlertInsufficientSecurity,
    AlertInternalError,
    AlertMissingExtension,
    AlertNoRenegotiation,
    AlertProtocolVersion,
    AlertRecordOverflow,
    AlertUnexpectedMessage,
    AlertUnknownCA,
    AlertUnsupportedExtension,
)
from ._callback import ClientHelloInfo, HandshakeContext, TicketContext
from ._configuration import TLSConfiguration, TLSCredential, load_castore
from ._connection import ConnectionState, TLSConnection
from ._constant import (
    AlertDescription,
    AlertLevel,
    Authentication,
    CertificateCompressionAlgorithm,
    CertificateStatusType,
    CipherSuite,
    ClientCertificateType,
    Compression,
    ContentType,
    ECCurveType,
    ECHClientHelloType,
    ECPointFormat,
    ExtensionType,
    HandshakeType,
    HashAlgorithm,
    HpkeAeadId,
    HpkeKdfId,
    HpkeKemId,
    KeyExchange,
    KeyUpdateMessageType,
    NamedGroup,
    NameType,
    PSKKeyExchangeMode,
    SignatureAlgorithm,
    SignatureScheme,
    Symmetric,
    TLSEnum,
    TLSVersion,
)
from ._enum import (
    ClientHelloType,
    ClientState,
    Direction,
    ECHStatus,
    Epoch,
    Protocol,
    ServerState,
    Shutdown,
    Status,
    VerifyMode,
)
from ._exception import (
    TLSAlert,
    TLSEOFError,
    TLSError,
    TLSLocalAlert,
    TLSRemoteAlert,
    TLSWantReadError,
)
from ._extension import (
    CertStatusRequestExtension,
    ClientALPNExtension,
    ClientALPSExtension,
    ClientEarlyDataExtension,
    ClientECHExtension,
    ClientHelloPaddingExtension,
    ClientKeyShareExtension,
    ClientNPNExtension,
    ClientPHAExtension,
    ClientPSKExtension,
    ClientSCTExtension,
    ClientSNIExtension,
    ClientStatusRequestExtension,
    ClientSupportedGroupsExtension,
    ClientSupportedVersionsExtension,
    CompressedCertificateExtension,
    CookieExtension,
    EarlyDataExtension,
    ECHConfig,
    ECHConfigContents,
    ECHOuterExtension,
    ECPointFormatsExtension,
    EmptyExtension,
    EncryptThenMacExtension,
    ExtendedMasterSecretExtension,
    Extension,
    ExtensionsMessage,
    ExtensionSource,
    GenericExtension,
    HRRECHExtension,
    HRRKeyShareExtension,
    IntExtension,
    KeyShareEntry,
    OptionalExtensionsMessage,
    PrefixedBytesExtension,
    PrefixedIntListExtension,
    PSKIdentity,
    PSKKeyExchangeModesExtension,
    RenegotiationInfoExtension,
    ServerALPNExtension,
    ServerALPSExtension,
    ServerEarlyDataExtension,
    ServerECHExtensions,
    ServerKeyShareExtension,
    ServerNPNExtension,
    ServerPSKExtension,
    ServerSCTExtension,
    ServerSNIExtension,
    ServerStatusRequestExtension,
    ServerSupportedVersionExtension,
    SessionTicketExtension,
    SignatureAlgorithmsExtension,
)
from ._handshake import TLSHandshake
from ._handshake_client import TLSHandshakeClient
from ._handshake_server import TLSHandshakeServer
from ._key import load_certificate_public_key, load_pem_private_key
from ._keyexchange import load_pem_parameters
from ._message import (
    Certificate,
    CertificateEntry,
    CertificateRequest,
    CertificateRequestTLS12,
    CertificateRequestTLS13,
    CertificateStatus,
    CertificateTLS13,
    CertificateVerify,
    CertificateVerifyTLS12,
    ClientHello,
    ClientKeyExchange,
    CompressedCertificate,
    EncryptedExtensions,
    EndOfEarlyData,
    Finished,
    Handshake,
    HandshakeMessage,
    HelloRequest,
    KeyUpdate,
    NewSessionTicket,
    NewSessionTicketTLS13,
    NextProtocol,
    ServerHello,
    ServerHelloDone,
    ServerKeyExchange,
)
from ._session import TicketAEAD, TLSSession
from ._supported import (
    CERTIFICATE_COMPRESSIONS,
    DSA_SIGNATURE_ALGORITHMS,
    ECC_GROUPS,
    ECDSA_SIGNATURE_ALGORITHMS,
    EDDSA_SIGNATURE_ALGORITHMS,
    FFDHE_GROUPS,
    KEM_GROUPS,
    RSA_PKCS1_SIGNATURE_ALGORITHMS,
    RSA_PSS_PSS_SIGNATURE_ALGORITHMS,
    RSA_PSS_RSAE_SIGNATURE_ALGORITHMS,
    RSA_SIGNATURE_ALGORITHMS,
    SIGNATURE_ALGORITHMS,
    SUPPORTED_GROUPS,
    TLS_VERSIONS,
)
from ._symmetric import KeyMaterial, NullCipher, TLSCipher
from ._transcript import KeyDeriver, KeySchedule, Transcript
from ._x509_validator import Validator

__all__ = [
    "CERTIFICATE_COMPRESSIONS",
    "DSA_SIGNATURE_ALGORITHMS",
    "ECC_GROUPS",
    "ECDSA_SIGNATURE_ALGORITHMS",
    "EDDSA_SIGNATURE_ALGORITHMS",
    "FFDHE_GROUPS",
    "KEM_GROUPS",
    "RSA_PKCS1_SIGNATURE_ALGORITHMS",
    "RSA_PSS_PSS_SIGNATURE_ALGORITHMS",
    "RSA_PSS_RSAE_SIGNATURE_ALGORITHMS",
    "RSA_SIGNATURE_ALGORITHMS",
    "SIGNATURE_ALGORITHMS",
    "SUPPORTED_GROUPS",
    "TLS_VERSIONS",
    "Alert",
    "AlertBadCertificate",
    "AlertBadRecordMac",
    "AlertCertificateExpired",
    "AlertCertificateRequired",
    "AlertDecodeError",
    "AlertDecryptError",
    "AlertDescription",
    "AlertECHRequired",
    "AlertException",
    "AlertHandshakeFailure",
    "AlertIllegalParameter",
    "AlertInappropriateFallback",
    "AlertInsufficientSecurity",
    "AlertInternalError",
    "AlertLevel",
    "AlertMissingExtension",
    "AlertNoRenegotiation",
    "AlertProtocolVersion",
    "AlertRecordOverflow",
    "AlertUnexpectedMessage",
    "AlertUnknownCA",
    "AlertUnsupportedExtension",
    "Authentication",
    "CertStatusRequestExtension",
    "Certificate",
    "CertificateCompressionAlgorithm",
    "CertificateEntry",
    "CertificateRequest",
    "CertificateRequestTLS12",
    "CertificateRequestTLS13",
    "CertificateStatus",
    "CertificateStatusType",
    "CertificateTLS13",
    "CertificateVerify",
    "CertificateVerifyTLS12",
    "CipherSuite",
    "ClientALPNExtension",
    "ClientALPSExtension",
    "ClientCertificateType",
    "ClientECHExtension",
    "ClientEarlyDataExtension",
    "ClientHello",
    "ClientHelloInfo",
    "ClientHelloPaddingExtension",
    "ClientHelloType",
    "ClientKeyExchange",
    "ClientKeyShareExtension",
    "ClientNPNExtension",
    "ClientPHAExtension",
    "ClientPSKExtension",
    "ClientSCTExtension",
    "ClientSNIExtension",
    "ClientState",
    "ClientStatusRequestExtension",
    "ClientSupportedGroupsExtension",
    "ClientSupportedVersionsExtension",
    "CompressedCertificate",
    "CompressedCertificateExtension",
    "Compression",
    "ConnectionState",
    "ContentType",
    "CookieExtension",
    "Direction",
    "ECCurveType",
    "ECHClientHelloType",
    "ECHConfig",
    "ECHConfigContents",
    "ECHOuterExtension",
    "ECHStatus",
    "ECPointFormat",
    "ECPointFormatsExtension",
    "EarlyDataExtension",
    "EmptyExtension",
    "EncryptThenMacExtension",
    "EncryptedExtensions",
    "EndOfEarlyData",
    "Epoch",
    "ExtendedMasterSecretExtension",
    "Extension",
    "ExtensionSource",
    "ExtensionType",
    "ExtensionsMessage",
    "Finished",
    "GenericExtension",
    "HRRECHExtension",
    "HRRKeyShareExtension",
    "Handshake",
    "HandshakeContext",
    "HandshakeMessage",
    "HandshakeType",
    "HashAlgorithm",
    "HelloRequest",
    "HpkeAeadId",
    "HpkeKdfId",
    "HpkeKemId",
    "IntExtension",
    "KeyDeriver",
    "KeyExchange",
    "KeyMaterial",
    "KeySchedule",
    "KeyShareEntry",
    "KeyUpdate",
    "KeyUpdateMessageType",
    "NameType",
    "NamedGroup",
    "NewSessionTicket",
    "NewSessionTicketTLS13",
    "NextProtocol",
    "NullCipher",
    "OptionalExtensionsMessage",
    "PSKIdentity",
    "PSKKeyExchangeMode",
    "PSKKeyExchangeModesExtension",
    "PrefixedBytesExtension",
    "PrefixedIntListExtension",
    "Protocol",
    "RenegotiationInfoExtension",
    "ServerALPNExtension",
    "ServerALPSExtension",
    "ServerECHExtensions",
    "ServerEarlyDataExtension",
    "ServerHello",
    "ServerHelloDone",
    "ServerKeyExchange",
    "ServerKeyShareExtension",
    "ServerNPNExtension",
    "ServerPSKExtension",
    "ServerSCTExtension",
    "ServerSNIExtension",
    "ServerState",
    "ServerStatusRequestExtension",
    "ServerSupportedVersionExtension",
    "SessionTicketExtension",
    "Shutdown",
    "SignatureAlgorithm",
    "SignatureAlgorithmsExtension",
    "SignatureScheme",
    "Status",
    "Symmetric",
    "TLSAlert",
    "TLSCipher",
    "TLSConfiguration",
    "TLSConnection",
    "TLSCredential",
    "TLSEOFError",
    "TLSEnum",
    "TLSError",
    "TLSHandshake",
    "TLSHandshakeClient",
    "TLSHandshakeServer",
    "TLSLocalAlert",
    "TLSRemoteAlert",
    "TLSSession",
    "TLSVersion",
    "TLSWantReadError",
    "TicketAEAD",
    "TicketContext",
    "Transcript",
    "Validator",
    "VerifyMode",
    "load_castore",
    "load_certificate_public_key",
    "load_pem_parameters",
    "load_pem_private_key",
]


__locals = locals()
for __name in __all__:
    if not __name.startswith("__"):
        __obj = __locals[__name]
        if hasattr(__obj, "__module__"):
            setattr(__obj, "__module__", "simple_tls.tls")
