# Copyright (c) 2026 The simple-tls Contributors

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the “Software”), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from __future__ import annotations

from ._alert import (
    AlertBadCertificate,
    AlertBadRecordMac,
    AlertCertificateExpired,
    AlertCertificateRequired,
    AlertDecodeError,
    AlertDecryptError,
    AlertECHRequired,
    AlertException,
    AlertHandshakeFailure,
    AlertIllegalParameter,
    AlertInappropriateFallback,
    AlertInsufficientSecurity,
    AlertInternalError,
    AlertMissingExtension,
    AlertNoRenegotiation,
    AlertProtocolVersion,
    AlertRecordOverflow,
    AlertUnexpectedMessage,
    AlertUnknownCA,
    AlertUnsupportedExtension,
    CustomAlert,
)
from ._cipher import NullCipher, TLSCipher
from ._common import (
    MD5_SHA1,
    MD5_SHA1_Hash,
    create_signature,
    get_algorithm,
    get_hash,
    verify_signature,
)
from ._connection import ConnectionState, TLSConnection
from ._constant import (
    CLIENT_CONTEXT_STRING,
    DSA_SIGNATURE_ALGORITHMS,
    ECC_GROUPS,
    ECDSA_SIGNATURE_ALGORITHMS,
    EDDSA_SIGNATURE_ALGORITHMS,
    FFDHE_GROUPS,
    GREASES,
    KEM_GROUPS,
    RSA_PKCS1_SIGNATURE_ALGORITHMS,
    RSA_PSS_PSS_SIGNATURE_ALGORITHMS,
    RSA_PSS_RSAE_SIGNATURE_ALGORITHMS,
    RSA_SIGNATURE_ALGORITHMS,
    SERVER_CONTEXT_STRING,
    SIGNATURE_ALGORITHMS,
    TLS11_DOWNGRADE_SENTINEL,
    TLS12_DOWNGRADE_SENTINEL,
    TLS13_HRR_SENTINEL,
    AlertDescription,
    AlertLevel,
    Authentication,
    CertificateCompressionAlgorithm,
    CertificateStatusType,
    CertificateType,
    CipherSuite,
    ClientCertificateType,
    Compression,
    ContentType,
    ECCurveType,
    ECHClientHelloType,
    ECPointFormat,
    ExtensionType,
    HandshakeType,
    HashAlgorithm,
    HpkeAeadId,
    HpkeKdfId,
    HpkeKemId,
    KeyExchange,
    KeyUpdateMessageType,
    NamedGroup,
    NameType,
    PSKKeyExchangeMode,
    SignatureAlgorithm,
    SignatureScheme,
    Symmetric,
    TLSEnum,
    TLSVersion,
)
from ._context import TLSContext
from ._enum import (
    ClientHelloType,
    ClientState,
    Direction,
    ECHStatus,
    Epoch,
    ServerState,
    Shutdown,
    Status,
    TLSSessionType,
    TLSVerifyMode,
)
from ._exception import (
    TLSAlert,
    TLSEOFError,
    TLSError,
    TLSLocalAlert,
    TLSRemoteAlert,
    TLSWantReadError,
)
from ._extension import (
    COMPRESSIBLE_EXTENSIONS,
    CertStatusRequestExtension,
    ClientALPNExtension,
    ClientALPSExtension,
    ClientEarlyDataExtension,
    ClientECHExtension,
    ClientHelloPaddingExtension,
    ClientKeyShareExtension,
    ClientNPNExtension,
    ClientPHAExtension,
    ClientPSKExtension,
    ClientSCTExtension,
    ClientSNIExtension,
    ClientStatusRequestExtension,
    ClientSupportedGroupsExtension,
    ClientSupportedVersionsExtension,
    CompressedCertificateExtension,
    CookieExtension,
    EarlyDataExtension,
    ECHConfig,
    ECHConfigContents,
    ECHOuterExtension,
    ECPointFormatsExtension,
    EmptyExtension,
    EncryptThenMacExtension,
    ExtendedMasterSecretExtension,
    ExtensionsMessage,
    ExtensionSource,
    GenericExtension,
    HRRECHExtension,
    HRRKeyShareExtension,
    IntExtension,
    KeyShareEntry,
    OptionalExtensionsMessage,
    PrefixedBytesExtension,
    PrefixedIntListExtension,
    PSKIdentity,
    PSKKeyExchangeModesExtension,
    RenegotiationInfoExtension,
    ServerALPNExtension,
    ServerALPSExtension,
    ServerEarlyDataExtension,
    ServerECHExtensions,
    ServerKeyShareExtension,
    ServerNPNExtension,
    ServerPSKExtension,
    ServerSCTExtension,
    ServerSNIExtension,
    ServerStatusRequestExtension,
    ServerSupportedVersionExtension,
    SessionTicketExtension,
    SignatureAlgorithmsExtension,
    TLSExtension,
)
from ._handshake import ECHConfigContent, TLSHandshake
from ._handshake_client import TLSHandshakeClient
from ._handshake_server import TLSHandshakeServer
from ._keyexchange import (
    ECDHKeyExchange,
    FFDHKeyExchange,
    KEMKeyExchange,
)
from ._message import (
    Alert,
    ApplicationData,
    Certificate,
    CertificateEntry,
    CertificateRequest,
    CertificateRequestTLS12,
    CertificateRequestTLS13,
    CertificateStatus,
    CertificateTLS13,
    CertificateVerify,
    CertificateVerifyTLS12,
    ChangeCipherSpec,
    ClientHello,
    ClientKeyExchange,
    CompressedCertificate,
    EncryptedExtensions,
    EndOfEarlyData,
    Finished,
    Handshake,
    HandshakeMessage,
    HelloRequest,
    KeyUpdate,
    Message,
    NewSessionTicket,
    NewSessionTicketTLS13,
    NextProtocol,
    ServerHello,
    ServerHelloDone,
    ServerKeyExchange,
)
from ._session import TLSSession
from ._transcript import KeyDeriver, KeySchedule, Transcript
from ._x509_validator import EKUValidator, SANValidator, Validator

__all__ = [
    "AlertBadCertificate",
    "AlertBadRecordMac",
    "AlertCertificateExpired",
    "AlertCertificateRequired",
    "AlertDecodeError",
    "AlertDecryptError",
    "AlertECHRequired",
    "AlertException",
    "AlertHandshakeFailure",
    "AlertIllegalParameter",
    "AlertInappropriateFallback",
    "AlertInsufficientSecurity",
    "AlertInternalError",
    "AlertMissingExtension",
    "AlertNoRenegotiation",
    "AlertProtocolVersion",
    "AlertRecordOverflow",
    "AlertUnexpectedMessage",
    "AlertUnknownCA",
    "AlertUnsupportedExtension",
    "CustomAlert",
    "NullCipher",
    "TLSCipher",
    "MD5_SHA1",
    "MD5_SHA1_Hash",
    "create_signature",
    "get_algorithm",
    "get_hash",
    "verify_signature",
    "ConnectionState",
    "TLSConnection",
    "CLIENT_CONTEXT_STRING",
    "DSA_SIGNATURE_ALGORITHMS",
    "ECC_GROUPS",
    "ECDSA_SIGNATURE_ALGORITHMS",
    "EDDSA_SIGNATURE_ALGORITHMS",
    "FFDHE_GROUPS",
    "GREASES",
    "KEM_GROUPS",
    "RSA_PKCS1_SIGNATURE_ALGORITHMS",
    "RSA_PSS_PSS_SIGNATURE_ALGORITHMS",
    "RSA_PSS_RSAE_SIGNATURE_ALGORITHMS",
    "RSA_SIGNATURE_ALGORITHMS",
    "SERVER_CONTEXT_STRING",
    "SIGNATURE_ALGORITHMS",
    "TLS11_DOWNGRADE_SENTINEL",
    "TLS12_DOWNGRADE_SENTINEL",
    "TLS13_HRR_SENTINEL",
    "AlertDescription",
    "AlertLevel",
    "Authentication",
    "CertificateCompressionAlgorithm",
    "CertificateStatusType",
    "CertificateType",
    "CipherSuite",
    "ClientCertificateType",
    "Compression",
    "ContentType",
    "ECCurveType",
    "ECHClientHelloType",
    "ECPointFormat",
    "ExtensionType",
    "HandshakeType",
    "HashAlgorithm",
    "HpkeAeadId",
    "HpkeKdfId",
    "HpkeKemId",
    "KeyExchange",
    "KeyUpdateMessageType",
    "NamedGroup",
    "NameType",
    "PSKKeyExchangeMode",
    "SignatureAlgorithm",
    "SignatureScheme",
    "Symmetric",
    "TLSEnum",
    "TLSVersion",
    "TLSContext",
    "ClientHelloType",
    "ClientState",
    "Direction",
    "ECHStatus",
    "Epoch",
    "ServerState",
    "Shutdown",
    "Status",
    "TLSSessionType",
    "TLSVerifyMode",
    "TLSAlert",
    "TLSEOFError",
    "TLSError",
    "TLSLocalAlert",
    "TLSRemoteAlert",
    "TLSWantReadError",
    "COMPRESSIBLE_EXTENSIONS",
    "CertStatusRequestExtension",
    "ClientALPNExtension",
    "ClientALPSExtension",
    "ClientEarlyDataExtension",
    "ClientECHExtension",
    "ClientHelloPaddingExtension",
    "ClientKeyShareExtension",
    "ClientNPNExtension",
    "ClientPHAExtension",
    "ClientPSKExtension",
    "ClientSCTExtension",
    "ClientSNIExtension",
    "ClientStatusRequestExtension",
    "ClientSupportedGroupsExtension",
    "ClientSupportedVersionsExtension",
    "CompressedCertificateExtension",
    "CookieExtension",
    "EarlyDataExtension",
    "ECHConfig",
    "ECHConfigContents",
    "ECHOuterExtension",
    "ECPointFormatsExtension",
    "EmptyExtension",
    "EncryptThenMacExtension",
    "ExtendedMasterSecretExtension",
    "ExtensionsMessage",
    "ExtensionSource",
    "GenericExtension",
    "HRRECHExtension",
    "HRRKeyShareExtension",
    "IntExtension",
    "KeyShareEntry",
    "OptionalExtensionsMessage",
    "PrefixedBytesExtension",
    "PrefixedIntListExtension",
    "PSKIdentity",
    "PSKKeyExchangeModesExtension",
    "RenegotiationInfoExtension",
    "ServerALPNExtension",
    "ServerALPSExtension",
    "ServerEarlyDataExtension",
    "ServerECHExtensions",
    "ServerKeyShareExtension",
    "ServerNPNExtension",
    "ServerPSKExtension",
    "ServerSCTExtension",
    "ServerSNIExtension",
    "ServerStatusRequestExtension",
    "ServerSupportedVersionExtension",
    "SessionTicketExtension",
    "SignatureAlgorithmsExtension",
    "TLSExtension",
    "ECHConfigContent",
    "TLSHandshake",
    "TLSHandshakeClient",
    "TLSHandshakeServer",
    "FFDHKeyExchange",
    "ECDHKeyExchange",
    "KEMKeyExchange",
    "Alert",
    "ApplicationData",
    "Certificate",
    "CertificateEntry",
    "CertificateRequest",
    "CertificateRequestTLS12",
    "CertificateRequestTLS13",
    "CertificateStatus",
    "CertificateTLS13",
    "CertificateVerify",
    "CertificateVerifyTLS12",
    "ChangeCipherSpec",
    "ClientHello",
    "ClientKeyExchange",
    "CompressedCertificate",
    "EncryptedExtensions",
    "EndOfEarlyData",
    "Finished",
    "Handshake",
    "HandshakeMessage",
    "HelloRequest",
    "KeyUpdate",
    "Message",
    "NewSessionTicket",
    "NewSessionTicketTLS13",
    "NextProtocol",
    "ServerHello",
    "ServerHelloDone",
    "ServerKeyExchange",
    "TLSSession",
    "KeyDeriver",
    "KeySchedule",
    "Transcript",
    "EKUValidator",
    "SANValidator",
    "Validator",
]


__locals = locals()
for __name in __all__:
    if not __name.startswith("__"):
        __obj = __locals[__name]
        if hasattr(__obj, "__module__"):
            setattr(__obj, "__module__", "simple_tls.tls")  # noqa
